name: Post New YouTube Videos to X

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  post-to-x:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Cache for node_modules (unchanged, as it's fine)
    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # NEW: Step 1 of 3 for state files - Restore
    - name: Restore Bot State Cache
      id: restore-bot-state # Give this step an ID to reference its output
      uses: actions/cache/restore@v4 # Use the specific 'restore' action
      with:
        path: |
          last-posted.txt
          template-indices.json
        key: ${{ runner.os }}-bot-state-${{ github.run_id }} # Unique key for this run's potential save
        restore-keys: |
          ${{ runner.os }}-bot-state- # Search for previous states

    - name: Install dependencies
      run: npm install

    - name: Run bot script
      run: node post.js
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

    # NEW: Step 2 of 3 for state files - Save
    - name: Save Bot State Cache
      uses: actions/cache/save@v4 # Use the specific 'save' action
      with:
        path: |
          last-posted.txt
          template-indices.json
        key: ${{ steps.restore-bot-state.outputs.cache-primary-key }} # Use the key from the restore step
      if: success() # Only save if the previous steps were successful (optional, but good practice)
