name: YouTube to X Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  post-to-x:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Antz72/youtube-to-X-bot
          fetch-depth: 1

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache bot state (restore)
        uses: actions/cache@v4
        id: restore-bot-state
        with:
          path: |
            last-posted.txt
            template-indices.json
          # CORRECTED KEY: This uses a stable name for easy restoration.
          key: bot-state-${{ github.ref }}
          restore-keys: |
            bot-state-

      - name: Install dependencies
        run: npm install

      - name: Run posting script
        run: node post.js
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          DRY_RUN_MODE: 'false'

      - name: Cache bot state (save)
        uses: actions/cache/save@v4
        # This ensures the state is only saved on a successful run.
        if: success()
        with:
          path: |
            last-posted.txt
            template-indices.json
          # Use the same key to update the cache.
          key: bot-state-${{ github.ref }}
