name: YouTube to X Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  post-to-x:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Antz72/youtube-to-X-bot
          fetch-depth: 1

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # The node_modules cache is still a good idea
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # ---- START: ARTIFACT-BASED STATE MANAGEMENT ----
      - name: Download previous bot state
        uses: actions/download-artifact@v4
        with:
          name: bot-state
          path: . # Download to the current directory
        # Continue even if the artifact doesn't exist (for the first run)
        continue-on-error: true

      - name: Install dependencies
        run: npm install

      - name: Run posting script
        run: node post.js
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          DRY_RUN_MODE: 'false'

      - name: Upload new bot state
        if: success() # Only upload if the script ran successfully
        uses: actions/upload-artifact@v4
        with:
          name: bot-state
          path: |
            last-posted.txt
            template-indices.json
          # Overwrite the old artifact with the new state
          if-no-files-found: error # Fail if the state files are missing
