name: Post New YouTube Videos to X

on:
  schedule:
    # Run every 10 minutes (adjust this cron schedule if you want it more or less frequent)
    # The cron string '*/10 * * * *' means "at every 10th minute".
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  post-to-x:
    runs-on: ubuntu-latest # Uses the latest Ubuntu Linux environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Gets your code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Installs Node.js
      with:
        node-version: '18' # Specifies Node.js version 18

    - name: Cache Node.js modules and bot data
      uses: actions/cache@v4 # Caches installed modules and your last-posted.txt/template-indices.json
      with:
        path: |
          node_modules
          last-posted.txt
          template-indices.json
        # Key uses runner OS and a hash of package-lock.json to create a unique cache key
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        # Restore keys provide fallbacks if the primary key doesn't hit
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      # This command reads your package.json and installs googleapis and twitter-api-v2
      run: npm install

    - name: Run bot script
      run: node post.js # Executes your main bot script
      env:
        # These are your environment variables (secrets) that the script needs
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
