name: Post New YouTube Videos to X

on:
  schedule:
    # Run every 30 minutes (adjust this cron schedule if you want it more or less frequent)
    # The cron string '*/30 * * * *' means "at every 30th minute".
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  post-to-x:
    runs-on: ubuntu-latest # Uses the latest Ubuntu Linux environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Gets your code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Installs Node.js
      with:
        node-version: '18' # Specifies Node.js version 18

    # Old 'Cache Node.js modules and bot data' step is being replaced/split

    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache Bot State Files
      uses: actions/cache@v4
      with:
        path: |
          last-posted.txt
          template-indices.json
        key: ${{ runner.os }}-bot-state-${{ github.run_id }} # Unique key for saving this run's state
        restore-keys: |
          ${{ runner.os }}-bot-state- # Restore from the latest state cache
        save-always: true # Crucial: Ensures changes to these files are saved back to the cache

    - name: Install dependencies
      run: npm install # This command reads your package.json and installs googleapis and twitter-api-v2

    - name: Run bot script
      run: node post.js # Executes your main bot script
      env:
        # These are your environment variables (secrets) that the script needs
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
